#!/bin/sh

set -e

case "$1" in
    configure|reconfigure)
        adduser --system --disabled-password --disabled-login --home /var/run/lldpd \
       	    --no-create-home --quiet --force-badname --group _lldpd

        for i in /usr/sbin/lldpcli; do
            if ! dpkg-statoverride --list $i > /dev/null 2>&1; then
                dpkg-statoverride --update --add _lldpd adm 4750 $i
            fi
        done
        ;;
esac

# Automatically added by dh_installinit
if [ -x "/etc/init.d/lldpd" ] || [ -e "/etc/init/lldpd.conf" ]; then
	if [ ! -e "/etc/init/lldpd.conf" ]; then
		update-rc.d lldpd defaults >/dev/null
	fi
	invoke-rc.d lldpd start || exit $?
fi
# End automatically added section
# Automatically added by dh_installinit
update-rc.d -f lldpd remove >/dev/null || exit $?
# End automatically added section
# Automatically added by dh_makeshlibs
if [ "$1" = "configure" ]; then
	ldconfig
fi
# End automatically added section


exit 0
